#define IDD_SETTINGS     2500
#define IDD_SETTINGS_2  12500

#define IDX_SETTINGS_SHOW_DOTS              2501
#define IDX_SETTINGS_SHOW_REAL_FILE_ICONS   2502
#define IDX_SETTINGS_SHOW_SYSTEM_MENU       2503
#define IDX_SETTINGS_FULL_ROW               2504
#define IDX_SETTINGS_SHOW_GRID              2505
#define IDX_SETTINGS_SINGLE_CLICK           2506
#define IDX_SETTINGS_ALTERNATIVE_SELECTION  2507
#define IDX_SETTINGS_LARGE_PAGES            2508
#define IDX_SETTINGS_WANT_ARC_HISTORY       2509
#define IDX_SETTINGS_WANT_PATH_HISTORY      2510
#define IDX_SETTINGS_WANT_COPY_HISTORY      2511
#define IDX_SETTINGS_WANT_FOLDER_HISTORY    2512
#define IDX_SETTINGS_LOWERCASE_HASHES       2513

// **************** SSS Modification Start ****************
#define IDX_SETTINGS_SIZE_FORMAT            2526
#define IDX_SETTINGS_DELETE_AFTER_EXTRACT   2527
#define IDX_SETTINGS_DELETE_PERMANENTLY     2528

#define IDD_SETTINGS_EXTRACT                12900
#define IDD_SETTINGS_EXTRACT_2             12910
// **************** SSS Modification Start (extraction settings) ****************
#define IDX_SETTINGS_AUTO_QUERY_CLOUD       2530
#define IDX_SETTINGS_AUTO_MATCH_LOCAL       2531
#define IDX_SETTINGS_MATCH_PRIORITY         2532
#define IDX_SETTINGS_AUTO_SHOW_PASSWORD     2533
#define IDX_SETTINGS_PASSWORD_BOOK          2534
#define IDX_SETTINGS_IMPORT_BOOK            2535
#define IDX_SETTINGS_API_URL                2536
#define IDX_SETTINGS_API_APP_ID             2537
#define IDX_SETTINGS_API_AES_KEY            2538
#define IDX_SETTINGS_API_SIGNING_KEY        2539
#define IDX_SETTINGS_API_PACKAGE_NAME       2540
#define IDX_SETTINGS_API_FINGERPRINT        2541
#define IDT_SETTINGS_GROUP_AUTOMATCH        2542
#define IDT_SETTINGS_GROUP_BOOK             2543
// 优先级下拉项（语言资源 ID，非控件）
#define IDX_SETTINGS_PRIORITY_LOCAL_CLOUD   2544
#define IDX_SETTINGS_PRIORITY_CLOUD_LOCAL   2545
// 静态标签
#define IDT_SETTINGS_API_URL                2546
#define IDT_SETTINGS_API_APP_ID             2547
#define IDT_SETTINGS_API_AES_KEY            2548
#define IDT_SETTINGS_API_SIGNING_KEY        2549
#define IDT_SETTINGS_API_PACKAGE_NAME       2550
#define IDT_SETTINGS_API_FINGERPRINT        2551
#define IDT_SETTINGS_MATCH_PRIORITY         2552
#define IDX_SETTINGS_API_PROTOCOL_VERSION   2580
#define IDX_SETTINGS_API_TIMEOUT_SECONDS    2581
#define IDT_SETTINGS_API_PROTOCOL_VERSION   2582
#define IDT_SETTINGS_API_TIMEOUT_SECONDS    2583
// **************** SSS Modification End ****************
// **************** SSS Modification End ****************
#define IDT_SETTINGS_FONT_GROUP           2514
#define IDT_SETTINGS_FONT_ADDRESSBAR      2517
#define IDC_SETTINGS_FONT_ADDRESSBAR      2518
#define IDT_SETTINGS_FONT_LIST            2519
#define IDC_SETTINGS_FONT_LIST            2520
#define IDT_SETTINGS_FONT_STATUSBAR       2521
#define IDC_SETTINGS_FONT_STATUSBAR       2522
#define IDT_SETTINGS_FONT_DIALOG          2523
#define IDC_SETTINGS_FONT_DIALOG          2524
#define IDT_SETTINGS_FONT_DEFAULT          2525
// **************** SSS Modification End ****************


// #define IDT_SETTINGS_MEM     100
// #define IDC_SETTINGS_MEM     101
// #define IDT_SETTINGS_MEM_RAM 102
// #define IDT_COMPRESS_MEMORY  4017
